### ISSUE TITLE
Python exception when selecting some uarches

### ISSUE THREAD

**Issue by pervognsen** [andreas-abel/uiCA#1]
First off, congrats on the announcement and initial release! I'm excited to start using it in my work.

I tried using the online version with this block: https://gist.github.com/pervognsen/5e081b19720a8d6954e28f187b50beff

It works on Skylake but when selecting some other uarches like Ice Lake I get the following Python error message:

    Traceback (most recent call last):
      File "/uiCA/uiCA.py", line 2413, in <module>
        main()
      File "/uiCA/uiCA.py", line 2363, in main
        TP = float(uopsForRelRound[-1][lastApplicableInstr][-1].retired
    IndexError: list index out of range

**Comment by andreas-abel** [comment]
Thanks for reporting. It should be fixed now.
