### ISSUE TITLE
Strange WAW/WAR-dependence edge in dependency graph

### ISSUE THREAD

**Issue by amonakov** [andreas-abel/uiCA#21]
For the following testcase (short link: https://bit.ly/3v1QfWV )
```
loop:
add rax, [rsi]
adc rax, [rsi]
dec rcx
jnz loop
```
There's the expected critical path over RAX updates, plus unexpected two-cycle critical path that goes over the carry flag:

![b41d13c23d9d4444ad7886107285db42_dep](https://user-images.githubusercontent.com/1997391/208400492-e811c18b-4d6b-4f13-a9c6-39917d3f2f9a.svg)

I'm surprised to see the backward edge from CF to the first instruction there.

**Comment by andreas-abel** [comment]
The add instruction reads RAX and writes the carry flag (this is the forward edge); the adc instruction reads the carry flag and writes RAX (this is the backward edge).

**Comment by amonakov** [comment]
Ah, sorry... Thanks for the explanation. I take it the items in a rectangle correspond just to instruction inputs (and outputs are not explicitly visible)?

Out of curiosity, have you explored other ways to visualize the dependency graph?

**Comment by andreas-abel** [comment]
> I take it the items in a rectangle correspond just to instruction inputs (and outputs are not explicitly visible)?

Yes, they are only implicitly visible as the input to the next instruction (and outputs that are never read are ignored, as they are not really relevant in this context).

> Out of curiosity, have you explored other ways to visualize the dependency graph?

I have tried a few ways, and this was the best I could find so far. But there is certainly room for improvement.
