### ISSUE TITLE
k0 ignores register dependencies

### ISSUE THREAD

**Issue by TellowKrinkle** [andreas-abel/uiCA#23]
```asm
kmovd eax, k1
kmovd k1, eax
kmovd edx, k0
kmovd k0, edx
```
On uica.uops.info: https://bit.ly/3Wn5k0E

Expected:
The k0 and k1 instructions work the same

Actual:
<img width="997" alt="image" src="https://user-images.githubusercontent.com/3315070/213897507-3b896131-7f95-4054-b958-4d35cb7ca496.png">

**Comment by chriselrod** [comment]
Another example https://bit.ly/3TWBQHd
