### ISSUE TITLE
Type checker errors

### ISSUE THREAD

**Issue by adsharma** [andreas-abel/uiCA#3]
I used pyright and it reported the following errors

https://paste.ubuntu.com/p/g3RxCsPrcC/

**Comment by andreas-abel** [comment]
Thanks. The first two errors can be avoided by following the installation instructions in the README (in particular, "pip3 install plotly"). Many of the other errors appear to be false positives.

**Comment by adsharma** [comment]
That's a large list of errors from a type checker - some of which may be real issues (like forgetting to check for none or detection of paths where  a certain variable may not be initialized).

Also some low hanging fruit:

uiCA.py:1781:9: F841 local variable 'allInputOperands' is assigned to but never used
uiCA.py:2632:5: F841 local variable 'tableWidth' is assigned to but never used
