### ISSUE TITLE
web interface randomly throws errors

### ISSUE THREAD

**Issue by sarvl** [andreas-abel/uiCA#30]
with correct piece of code errors are reported

see screenshots:
![image](https://github.com/andreas-abel/uiCA/assets/95301979/198660de-f05a-4727-bca0-7aaec20cd9c3)
![image](https://github.com/andreas-abel/uiCA/assets/95301979/0cedb35a-40e2-460a-9bd2-da6b48d0e4bb)

it usually works after few tries
![image](https://github.com/andreas-abel/uiCA/assets/95301979/e896a959-1896-4872-8b85-b6cc7cd5fc00)

from what ive seen the specifc code and options do not matter

**Comment by andreas-abel** [comment]
This should now be fixed.
